name: SonarCloud Scan

on:
  push:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Set to your desired Java version

      - name: Build with Maven and Run SonarQube analysis
        run: |
          mvn clean install sonar:sonar \
            -Dsonar.organization=sabiaparveen1 \
            -Dsonar.projectKey=cloudevents-demo \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
