name: "sonar_cloud_scan_github_actions"
on:
  workflow_dispatch:

jobs:
  DemoSonarCloudSCan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run SonarQube analysis during build
        run: mvn clean install sonar:sonar -Dsonar.organization=sabiaparveen1 -Dsonar.projectKey=cloudevents-demo -Dsonar.login=${{ secrets.SONAR_TOKEN }}

